### ISSUE TITLE
aio_read doing synchronous stat when size parameter is null

### ISSUE THREAD

**Issue by siboulet** [ksperis/node-rados#9]
When calling aio_read() with a null size parameter, the module will call rados_stat() to get the object size and set size to the size of the object.

https://github.com/ksperis/node-rados/blob/master/rados.cc#L619-L630

This effectively turn the asynchronous aio_read call to be synchronous (that is the rados_stat() call is synchronous). Instead, the size parameter should be mandatory and an error should be returned, or the size could also default to DEFAULT_BUFFER_SIZE (defined in rados.h).

**Comment by ksperis** [comment]
Yes it's true, if the size is not specified, the async is only partial because of use of rados_stat() is synchronous. However, it permit to read a full object (Anyway asynchronously) without knowing its size. Another possibility would be to make an asynchronous call to rados_stat().
Meanwhile, it would be wise to make this clear in the documentation or examples.

**Comment by siboulet** [comment]
I looked at doing an asynchronous stat call, but that is not provided by librados so we would need to have our own NanAsyncWorker to do this (which requires a bit more work).

I think if someone wanted to do a full async read in a single call they should manually do a (blocking) ioctx.stat call first to get the length they want to read.

But another problem in the way full read are currently implemented (sync or async) is that it assumes the object doesn't change between the stat call and the read call. I think it would be better to read until EOF is reached, instead of using a stat.

**Comment by ksperis** [comment]
Yes I understand what you mean. But I'm not sure that there is the notion of EOF in librados for a complete reading.
Otherwise, we can also specify a default size for reading, per example python has default length set to 4096 for sync read : http://ceph.com/docs/master/rados/api/python/#rados.Ioctx.read
That would be the simple way.

**Comment by siboulet** [comment]
I think you ask to read say 4096 and know its EOF when librados returns less than 4096.

**Comment by ksperis** [comment]
I will do tests like this.

**Comment by ksperis** [comment]
Default read size is now 8192.
